apiVersion: v1
kind: Service
metadata:
  name: demo-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: demo-cluster-ip-service
  selector:
    name: simple-webapp-color-label
