apiVersion: v1

kind: Pod

metadata:
  name: web-pod

spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "sleep"
        - "3600"

      securityContext:
        runAsUser: 1000 # User from container level overrides user form pod level
        capabilities:
          add:
            - "MAC_ADMIN"

  securityContext:
    runAsUser: 1000
