apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    resourceNames: [ "blue", "orange" ]
    verbs: [ "list", "get", "create", "update", "delete" ]
  - apiGroups: [ "" ]
    verbs: [ "create" ]
    resources: [ "ConfigMap" ]
