apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flight-ticket.flights.com
spec:
  scope: Namespaced
  group: flights.com
  names:
    shortNames:
      - ft
    kind: FlightTicket
    plural: flight-ticket
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                from:
                  type: string
                to:
                  type: string
                number:
                  minimum: 1
                  maximum: 10
                  type: integer
