apiVersion: v1

kind: Pod

metadata:
  name: simple-webapp-color-name
  labels:
    name: simple-webapp-color-label

spec:
  containers:
    - name: simple-webapp-color-container
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: custom-secret-name
      envFrom:
        - secretRef:
            name: custom-secret-name
  volumes:
    - name: custom-secret-volume-name
      secret:
        secretName: custom-secret-name
