apiVersion: apps/v1

kind: Deployment

metadata:
  name: "my-app-deployment-name"
  labels:
    app: "my-app-label"
    type: "front-end-label"
    cost-center-location: "Ukraine"

spec:
  replicas: 6
  selector:
    matchLabels:
      type: "front-end-label"
  template:
    spec:
      containers:
        - name: "nginx-container"
          image: nginx:alpine-slim
    metadata:
      name: "my-app-pod"
      labels:
        app: "my-app-label"
        type: "front-end-label"
        cost-center-location: "Ukraine"
