apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-administrator-role-binding
roleRef:
  kind: ClusterRole
  name: cluster-administrator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: cluster-administrator
    apiGroup: rbac.authorization.k8s.io
