apiVersion: v1
kind: LimitRange
metadata:
  name: demo-limit-range-constraint-name
spec:
  limits:
    - default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 100m
        memory: 500Mi
      type: Container

### 1G  (Gigabyte) = 1,000,000,000 bytes
### 1M  (Megabyte) = 1,000,000 bytes
### 1K  (Kilobyte) = 1,000 bytes
### 1Gi (Gibibyte) = 1,073,741,824 bytes
### 1Mi (Mebibyte) = 1,048,576 bytes
### 1Ki (Kibibyte) = 1,024 bytes
