apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-resource-quota-name
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "10"
    limits.memory: "10Gi"

### 1G  (Gigabyte) = 1,000,000,000 bytes
### 1M  (Megabyte) = 1,000,000 bytes
### 1K  (Kilobyte) = 1,000 bytes
### 1Gi (Gibibyte) = 1,073,741,824 bytes
### 1Mi (Mebibyte) = 1,048,576 bytes
### 1Ki (Kibibyte) = 1,024 bytes
