apiVersion: v1

kind: ReplicationController

metadata:
  labels:
    app: "my-app-label"
    type: "front-end-label"
    cost-center-location: "Ukraine"
  name: "replication-controller-name"

spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: "nginx-container"
          image: nginx:alpine-slim
    metadata:
      name: "my-app-pod"
      labels:
        app: "my-app-label"
        type: "front-end-label"
        cost-center-location: "Ukraine"


