apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 10.10.30.4:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
    - command:
        - kube-apiserver
        - --encryption-provider-config=encryption-definition.yml  # add this line
      volumeMounts:
        - name: enc                           # add this line
          mountPath: /                        # add this line
          readonly: true                      # add this line
  volumes:
    - name: enc                             # add this line
      hostPath: # add this line
        path: /        # add this line
        type: DirectoryOrCreate             # add this line
