apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-name
spec:
  containers:
    - name: demo-pod-container
      image: data-processor

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: NotIn
                values:
                  - Small
              - key: size
                operator: In
                values:
                  - Large
                  - Medium
              - key: size
                operator: Exists
