apiVersion: v1

kind: Pod

metadata:
  name: simple-web-app-color

spec:
  containers:
    - name: simple-web-app-color-container
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: pink
