apiVersion: v1
kind: Config

current-context: kube-admin@kube-cluster

clusters:
  - name: kube-cluster
    cluster:
      certificate-authority: ca.crt
      server: https://kube-host-or-ip:6443

contexts:
  - name: kube-admin@kube-cluster
    context:
      user: kube-admin
      cluster: kube-cluster
      namespace: custom-namespace

users:
  - name: kube-admin
    user:
      client-key: admin.key
      client-certificate: admin.crt
