apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cron-job
spec:
  schedule: "0 0 0 * *"
  jobTemplate:
    spec:
      parallelism: 3
      completions: 3
      backoffLimit: 100
      template:
        spec:
          containers:
            - name: demo-cron-job-container
              image: ubuntu
          restartPolicy: Never
